import { SlashCommandBuilder } from 'discord.js';
import axios from 'axios';
import { logInfo, logError } from '../logger.js';
import { fetchGeminiResponse } from '../ai.js';

const fallbackQuotes = [
    { q: "The only limit to our realization of tomorrow is our doubts of today.", a: "Franklin D. Roosevelt" },
    { q: "In the middle of every difficulty lies opportunity.", a: "Albert Einstein" },
    { q: "Success is not final, failure is not fatal: It is the courage to continue that counts.", a: "Winston Churchill" },
];

export default {
    data: new SlashCommandBuilder()
        .setName('quote')
        .setDescription('Get a random motivational quote.'),
    async execute(interaction) {
        try {
            const [apiResponse] = await Promise.all([
                axios.get('https://zenquotes.io/api/random'),
            ]);

            const quote = apiResponse.data[0].q;
            const author = apiResponse.data[0].a;

            logInfo('Quote fetched successfully.', { quote, author });

            await interaction.reply({ content: `"${quote}"\n- ${author}`, ephemeral: false });
        } catch (error) {
            logError('Failed to fetch a quote from the API.', { error });

            try {
                const geminiQuote = await fetchGeminiResponse("Generate a motivational quote.");
                await interaction.reply({ content: `"${geminiQuote}"\n- Generated by AI`, ephemeral: false });
            } catch (geminiError) {
                logError('Failed to fetch a quote from Gemini API.', { geminiError });

                const fallback = fallbackQuotes[Math.floor(Math.random() * fallbackQuotes.length)];
                await interaction.reply({ content: `"${fallback.q}"\n- ${fallback.a}`, ephemeral: false });
            }
        }
    },
};
